// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfigPath():Promise<string>;

export function GetSystemStats():Promise<Record<string, any>>;

export function LoadConfig():Promise<Record<string, any>>;

export function SaveConfig(arg1:Record<string, any>):Promise<void>;
