// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetSettings():Promise<main.Settings>;

export function GetSystemStats():Promise<Record<string, any>>;

export function SaveSettings(arg1:main.Settings):Promise<void>;
