// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHistoryEntry(arg1, arg2) {
  return window['go']['main']['HistoryService']['AddHistoryEntry'](arg1, arg2);
}

export function LoadHistory() {
  return window['go']['main']['HistoryService']['LoadHistory']();
}
