// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function CleanupAllSessions():Promise<void>;

export function KillSession(arg1:string):Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function StartSession(arg1:number,arg2:number,arg3:string):Promise<string>;

export function WriteToTerminal(arg1:string,arg2:string):Promise<void>;
